batch_size: 6
channels: 1
classes: 4
input_size: 416
anchors:
  - [[10,13], [16,30], [33,23]]
  - [[30,61], [62,45], [59,119]]
  - [[116,90], [156,198], [373,326]]
epochs: 200
IoU: 0.5
CUDA: Enable
path:
  train: /workspace/data/dataset/train.txt
  test: /workspace/data/dataset/test.txt
  image: /workspace/data/dataset/image/
  classes: /workspace/data/class/classes.txt
  anchor: /workspace/data/anchor/anchors.txt
  weight: /workspace/weight/
  initial_weight: False
