batch_size: 6
num_channels: 1
classes:
    - A
    - B
    - C
    - D
height: 416
width: 416
anchors:
    - [[4, 10], [10, 4], [7, 7]]
    - [[8, 20], [20, 8], [14, 14]]
    - [[12, 30], [30, 12], [21, 21]]
num_epochs: 1000
TP_IoU: 0.5
NMS_IoU: 0.4
objectness: 0.8
learning_rate: 0.001
CUDA: True
path:
    train: ./dataset/train
    test: ./dataset/test
    image: ./dataset/image
    weight: ./dataset/weight
    weight_test: ./dataset/weight
    initial_weight: False
