batch_size: 6
channels: 1
input_size: 416
epochs: 200
IoU: 0.5
CUDA: Enable
path:
  train: /workspace/data/dataset/train.txt
  test: /workspace/data/dataset/test.txt
  image: /workspace/data/dataset/image/
  classes: /workspace/data/class/classes.txt
  anchor: /workspace/data/anchor/anchors.txt
  weight: /workspace/weight/
  initial_weight: False
