batch_size: 6
num_channels: 1
classes:
    - A
    - B
    - C
    - D
height: 448
width: 448
anchors:
    - [[5, 8], [5, 11], [5, 12]]
    - [[7, 9], [6, 12], [5, 15]]
    - [[8, 11], [8, 15], [10, 22]]
num_epochs: 1000
TP_IoU: 0.5
NMS_IoU: 0.001
confidency: 0.6
learning_rate: 1.0e-4
weight_decay: 1.0e-2
CUDA: True
path:
    train: ./dataset/train
    test: ./dataset/test
    image: ./dataset/image
    weight: ./dataset/weight
    weight_test: ./dataset/weight_test
    initial_weight: ./dataset/weight_test/2021-02-06_23-28-19_0307_37.46.pt
    # initial_weight: ./dataset/weight_test/2021-02-04_08-45-32_0277_42.08.pt for 416x416
    detect_weight: ./smd_weight.pt
