batch_size: 6
num_channels: 1
classes:
    - A
    - B
    - C
    - D
height: 416
width: 416
anchors:
    - [[4, 16], [8, 8], [16, 4]]
    - [[8, 32], [16, 16], [32, 8]]
    - [[16, 64], [32, 32], [64, 16]]
num_epochs: 500
TP_IoU: 0.5
NMS_IoU: 0.1
confidency: 0.5
learning_rate: 1.0e-4
weight_decay: 1.0e-2
CUDA: True
path:
    train: ./dataset/train
    test: ./dataset/test
    image: ./dataset/image
    weight: ./dataset/weight
    weight_test: ./dataset/weight_test
    initial_weight: False
    detect_weight: ./dataset/weight_test/2021-01-22_02-04-48_0068_1880.07.pt
