batch_size: 6
num_channels: 1
classes:
    - A
    - B
    - C
    - D
height: 416
width: 416
anchors:
    - [[3, 5], [5, 3], [4, 4]]
    - [[6, 10], [10, 6], [8, 8]]
    - [[12, 20], [20, 12], [16, 16]]
num_epochs: 500
TP_IoU: 0.5
NMS_IoU: 0.1
confidency: 0.5
learning_rate: 1.0e-3
weight_decay: 1.0e-2
CUDA: True
path:
    train: ./dataset/train
    test: ./dataset/test
    image: ./dataset/image
    weight: ./dataset/weight
    weight_test: ./dataset/weight_test
    initial_weight: False
    detect_weight: ./dataset/weight_test/2020-12-31_19-57-56_0200_595.49.pt
