batch_size: 6
num_channels: 1
classes:
    - A
    - B
    - C
height: 416
width: 416
anchors:
  - [[10,13], [16,30], [33,23]]
  - [[30,61], [62,45], [59,119]]
  - [[116,90], [156,198], [373,326]]
num_epochs: 200
TP_IoU: 0.5
NMS_IoU: 0.4
objectness: 0.8
CUDA: True
path:
  train: /workspace/dataset/train/
  test: /workspace/dataset/test/
  image: /workspace/dataset/image/
  weight: /workspace/dataset/weight/
  initial_weight: False
