batch_size: 6
num_channels: 1
classes:
    - A
    - B
    - C
    - D
height: 416
width: 416
anchors:
    - [[3, 5], [5, 3], [4, 4]]
    - [[6, 10], [10, 6], [8, 8]]
    - [[12, 20], [20, 12], [16, 16]]
num_epochs: 300
TP_IoU: 0.5
NMS_IoU: 0.2
objectness: 0.8
learning_rate: 1.0e-6
weight_decay: 1.0e-2
CUDA: True
path:
    train: ./dataset/train
    test: ./dataset/test
    image: ./dataset/image
    weight: ./dataset/weight
    weight_test: ./dataset/weight
    initial_weight: False
    detect_weight: ./dataset/weight/2020-12-19_05-40-15_0655_14066.18.pt
